name: Automated Testing Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  unit-testing:
    name: Jalankan Semua Tes (pytest)
    runs-on: ubuntu-latest

    steps:
      - name: 1. Mengambil salinan code baru
        uses: actions/checkout@v4

      - name: 2. Install 'uv' PM & Setup Python
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: '3.12' 

      - name: 3. Memasang Dependensi Proyek (Termasuk Dev Groups)
        run: uv sync --all-groups

      - name: 4. Membuat Folder Logs Sementara
        run: mkdir -p logs

      - name: 5.  Menyiapkan File Konfigurasi Dummy untuk Testing
        run: |
          mkdir -p config
          echo "${{ secrets.PIPELINE_CONFIG_CONTENT }}" > config/pipeline_config.yaml

      - name: 6. Eksekusi Pengujian
        run: uv run pytest -q --tb=short

      - name: 7. Bersihkan dan Hapus File Asli dari Server
        if: always()
        run: |
          rm -f config/pipeline_config.yaml
          echo "File konfigurasi rahasia berhasil dimusnahkan dari server."

